import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "./components/nav";
import Footer  from "./components/footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "nextjs",
  description: "Generated by create next app",
};

export default function RootLayout(
  {children} : Readonly<{ children: React.ReactNode; }> 
) {
  return (
    <html lang="en" className="antialiased max-w-xl mx-4 mt-8 lg:mx-auto">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}