import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Navbar } from "./components/nav";
import Footer from "./components/footer";
import { baseUrl } from "./components/sitemap";
import "./globals.css";

import fs from 'fs'
import path from 'path'

let Files: string[]  = [];
function ThroughDirectory(dir: string, fileType: any) {
  /** Recursively run throgh specified folder and store the files found in an array
   *  the build requires metadata, thats why this step is here
  */
  
  fs.readdirSync(dir).forEach(File => {
    const Absolute = path.join(dir, File);
      
    if (fs.statSync(Absolute).isDirectory()) {
      return ThroughDirectory(Absolute, fileType)
    } 
    
    else {
      return Files.push(Absolute);
    }
  });
}
// Recursively run throgh specified folder
ThroughDirectory("../public", [".jpeg", ".png"]);

// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Klifton's Portfolio App",
  description: "Generated by create-next-app",
  // baseURL
  metadataBase: new URL(baseUrl),
  // load images
  openGraph: {
    images: Files,
  },
};

export default function RootLayout(
  {children} : Readonly<{ children: React.ReactNode; }> 
) {
  return (
    <html lang="en" className="antialiased max-w-xl mx-4 mt-8 lg:mx-auto">
      <body>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}