import type { Metadata } from "next";
import { Inter } from "next/font/google";
import  Navbar  from "./components/nav";
import Footer from "./components/footer";
import { baseUrl } from "./components/sitemap";
import "./globals.css";

export const metadata: Metadata = {
  title: "Klifton's Portfolio App",
  description: "Generated by create-next-app",
};

export default function RootLayout(
  {children} : Readonly<{ children: React.ReactNode; }> 
) {
  return (
    <html lang="en" className="px-8 antialiased max-w-2xl mt-8 lg:mx-auto duration-300 scroll-py-5">
      <body className="transition-all">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}